# Generated by Django 3.2 on 2021-04-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Book',
            new_name='book',
        ),
    ]
